# Environment Args
output_root: '.'
pytorch_data_dir: './datasets'
submitting_to_aml: false

# Dataset args
train_dataset: "cocostuff"
val_dataset: "coco_validation50"
res: 336 #224 or 336

# Model Args
model_type: "clip-large" #vit or clip-large
activation_type: "token"
is_norm: False
is_high_res: False
dim: 1024 #384 or 1024

# Upsampling args
outlier_detection: True
upsampler_type: "jbu_4x_stack"
downsampler_type: "attention"
max_pad: 30 
max_zoom: 2
n_jitters: 2 
random_projection: 30
crf_weight: 0.001
filter_ent_weight: 0.0
tv_weight: 0.0

implicit_sup_weight: 1.0

# Training args
batch_size: 2
epochs: 1
num_gpus: 8
num_workers: 24
lr: 1e-3

# No need to change
hydra:
  run:
    dir: "."
  output_subdir: ~

